### ISSUE TITLE
Issue with SEO Title Assessor

### ISSUE THREAD

**Issue by Chris-CWZ** [meyt/vue-yoast#1]
May I know how the title is being assessed by the seo-assessor component? Because I think there is an issue with the title assessor. Even if I put in a title that's very very long(275 characters), the seo assessor feedback still tells me that my SEO Title is too short. Below is the exact feedback.

"The SEO title is too short. Use the space to add keyword variations or create compelling call-to-action copy."

Would appreciate any feedback on this please, thanks!

**Comment by meyt** [comment]
@Chris-CWZ SEO assessor has an attribute for title width that based on pixels (not chars). the problem is on demo and i forgot to set `titleWidth` property for `<seo-assesor>`.
