### ISSUE TITLE
“Please create an SEO title” warning

### ISSUE THREAD

**Issue by Chris-CWZ** [meyt/vue-yoast#2]
Hi, I'm having an issue where the SEO Assessor is returning me the "Please create an SEO title" warning despite already passing in the 'title' prop. 

![image](https://user-images.githubusercontent.com/23399596/103501262-9eb34680-4e88-11eb-8dca-236ed3595d93.png)

As you can see in the image above, upon opening the Vue inspector, the 'title' prop already has a value. Yet I'm still getting the  red warning "Please create an SEO title". The warning disappears when I make any changes to the title, i.e. removing or adding a character. It's like the SEOAssessor component is not reading the value **until there is a change to the value** despite it already being passed in. 

**Update:**
Even if you visit the demo site of the library(https://meyt.github.io/vue-yoast-demo/), the same bug exists there. Even though the Meta Title already has a value of "My Amazing Title", the Seo Assessor component is still showing the warning "Please create an SEO title." It's only until after you update the value of the Meta Title, then the SEO Assessor acknowledges the presence of the SEO title, despite the fact that there is **already a value for the Meta TItle.**

**Comment by meyt** [comment]
Hi @Chris-CWZ,
Its related to initial value of `titleWidth` which fixed in `v1.0.1`.
